name: Link Dockerise and run unit tests
run-name: ${{ github.actor }} Dockerise the app ðŸš€

on: [push]

jobs:
  launch-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Install docker
        run: sudo apt update && sudo apt install -y docker-ce

      - name: Docker version verify
        run: docker --version

      - name: Build the image
        run: docker build -t pythoncicd -f Dockerfile .

      - name: List Docker images 
        run: docker image ls

      - name: Containerise the app
        run: docker run --name pythonTestContainer pythoncicd
