name: Run python unit test
run-name: ${{ github.actor }} run unit test ðŸš€
on: [push]
jobs:
  launch-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - run: "${{github.actor}} launch pytest"
      - name: Run addition test
        uses: actions/checkout@v5
      - run: python -m unittest
      
